# Generated by Django 3.0.6 on 2020-05-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1024)),
                ('dl', models.DateTimeField()),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
